language: csharp
sudo: required
services:
  - docker
mono: latest
dotnet: 2.0.3
dist: trusty
install:
  - pip install --upgrade pip 
  - pip install aws-sam-cli
script: bash ./build.sh --target=TravisCI