version: '{build}'
image: Visual Studio 2017
install:
  - ps: python -m pip install --upgrade pip
  - ps: pip install requests[security]
  - ps: pip install --user aws-sam-cli
build_script:
  - ps: .\build.ps1 --target=AppVeyor
test: off